name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build project
        run: docker compose build

      - name: Setup test environment
        run: |
          docker compose up -d mysql nats
          sleep 5
          docker compose run web npm run db:init

      - name: Run linter
        run: docker compose run web npm run lint

      - name: Run typecheck
        run: docker compose run web npm run typecheck

      - name: Run tests
        run: docker compose run web npm test run
